--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      unam
-- Project :      fragmento4.DM1
-- Author :       din1eagle30@outlook.com
--
-- Date Created : Thursday, May 30, 2024 16:56:41
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: AUTO_F1_AEGG_S2 
--

CREATE TABLE AUTO_F1_AEGG_S2(
    AUTO_ID    NUMBER(10, 0)    NOT NULL,
    FOTO       BLOB             NOT NULL,
    CONSTRAINT PK5_1 PRIMARY KEY (AUTO_ID)
);



-- 
-- TABLE: CLIENTE_F3_AEGG_S2 
--

CREATE TABLE CLIENTE_F3_AEGG_S2(
    CLIENTE_ID            NUMBER(10, 0)    NOT NULL,
    NOMBRE                VARCHAR2(40)     NOT NULL,
    AP_PATERNO            VARCHAR2(40)     NOT NULL,
    AP_MATERNO            VARCHAR2(40),
    NUM_IDENTIFICACION    VARCHAR2(18)     NOT NULL,
    EMAIL                 VARCHAR2(500)    NOT NULL,
    CONSTRAINT PK1 PRIMARY KEY (CLIENTE_ID)
);



-- 
-- TABLE: STATUS_AUTO 
--

CREATE TABLE STATUS_AUTO(
    STATUS_AUTO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE             VARCHAR2(20)     NOT NULL,
    DESCRIPCION       VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (STATUS_AUTO_ID)
);



-- 
-- TABLE: HISTORICO_STATUS_AUTO_F1_AEGG_S2 
--

CREATE TABLE HISTORICO_STATUS_AUTO_F1_AEGG_S2(
    HISTORICO_STATUS_ID    NUMBER(10, 0)    NOT NULL,
    FECHA_STATUS                DATE             NOT NULL,
    STATUS_AUTO_ID              NUMBER(10, 0)    NOT NULL,
    AUTO_ID                     NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK11_1 PRIMARY KEY (HISTORICO_STATUS_ID), 
    CONSTRAINT RefSTATUS_AUTO2 FOREIGN KEY (STATUS_AUTO_ID)
    REFERENCES STATUS_AUTO(STATUS_AUTO_ID),
    CONSTRAINT RefAUTO_F1_AEGG_S25 FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F1_AEGG_S2(AUTO_ID)
);



-- 
-- TABLE: MARCA_R_AEGG_S2 
--

CREATE TABLE MARCA_R_AEGG_S2(
    MARCA_ID       NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (MARCA_ID)
);



-- 
-- TABLE: MODELO_R_AEGG_S2 
--

CREATE TABLE MODELO_R_AEGG_S2(
    MODELO_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    MARCA_ID       NUMBER(10, 0)    NOT NULL,    
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (MODELO_ID), 
    CONSTRAINT RefMARCA_R_AEGG_S21 FOREIGN KEY (MARCA_ID)
    REFERENCES MARCA_R_AEGG_S2(MARCA_ID)
);



-- 
-- TABLE: PAGO_AUTO_F3_AEGG_S2 
--

CREATE TABLE PAGO_AUTO_F3_AEGG_S2(
    CLIENTE_ID     NUMBER(10, 0)    NOT NULL,
    AUTO_ID        NUMBER(10, 0)    NOT NULL,
    FECHA_PAGO     DATE             NOT NULL,
    IMPORTE        NUMBER(8, 2)     NOT NULL,
    RECIBO_PAGO    BLOB             NOT NULL,
    CONSTRAINT PK2 PRIMARY KEY (CLIENTE_ID, AUTO_ID), 
    CONSTRAINT RefCLIENTE_F3_AEGG_S23 FOREIGN KEY (CLIENTE_ID)
    REFERENCES CLIENTE_F3_AEGG_S2(CLIENTE_ID),
    CONSTRAINT RefAUTO_F1_AEGG_S24 FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F1_AEGG_S2(AUTO_ID)
);



