--
-- ER/Studio 8.0 SQL Code Generation
-- Company :      unam
-- Project :      fragmento1.DM1
-- Author :       din1eagle30@outlook.com
--
-- Date Created : Thursday, May 30, 2024 17:00:12
-- Target DBMS : Oracle 11g
--

-- 
-- TABLE: MARCA_R_RDVG_S1 
--

CREATE TABLE MARCA_R_RDVG_S1(
    MARCA_ID       NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK10 PRIMARY KEY (MARCA_ID)
);



-- 
-- TABLE: MODELO_R_RDVG_S1 
--

CREATE TABLE MODELO_R_RDVG_S1(
    MODELO_ID      NUMBER(10, 0)    NOT NULL,
    CLAVE          VARCHAR2(50)     NOT NULL,
    DESCRIPCION    VARCHAR2(500)    NOT NULL,
    MARCA_ID       NUMBER(10, 0)    NOT NULL,
    ACTIVO         NUMBER(1, 0)     NOT NULL,
    CONSTRAINT PK12 PRIMARY KEY (MODELO_ID), 
    CONSTRAINT RefMARCA_R_RDVG_S111 FOREIGN KEY (MARCA_ID)
    REFERENCES MARCA_R_RDVG_S1(MARCA_ID)
);



-- 
-- TABLE: PAIS_F1_RDVG_S1 
--

CREATE TABLE PAIS_F1_RDVG_S1(
    PAIS_ID    NUMBER(10, 0)    NOT NULL,
    NOMBRE     VARCHAR2(40)     NOT NULL,
    CLAVE      VARCHAR2(4)      NOT NULL,
    REGION     VARCHAR2(3)      NOT NULL,
    CONSTRAINT PK9 PRIMARY KEY (PAIS_ID)
);



-- 
-- TABLE: SUCURSAL_F2_RDVG_S1 
--

CREATE TABLE SUCURSAL_F2_RDVG_S1(
    SUCURSAL_ID          NUMBER(10, 0)    NOT NULL,
    NOMBRE               VARCHAR2(40)     NOT NULL,
    CLAVE                VARCHAR2(8)      NOT NULL,
    SUCURSAL_ANEXA_ID    NUMBER(10, 0),
    PAIS_ID              NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK4 PRIMARY KEY (SUCURSAL_ID), 
    CONSTRAINT RefPAIS_F1_RDVG_S15 FOREIGN KEY (PAIS_ID)
    REFERENCES PAIS_F1_RDVG_S1(PAIS_ID)
);



-- 
-- TABLE: STATUS_AUTO 
--

CREATE TABLE STATUS_AUTO(
    STATUS_AUTO_ID    NUMBER(10, 0)    NOT NULL,
    CLAVE             VARCHAR2(20)     NOT NULL,
    DESCRIPCION       VARCHAR2(40)     NOT NULL,
    CONSTRAINT PK6 PRIMARY KEY (STATUS_AUTO_ID)
);



-- 
-- TABLE: AUTO_F2_RDVG_S1 
--

CREATE TABLE AUTO_F2_RDVG_S1(
    AUTO_ID           NUMBER(10, 0)    NOT NULL,
    ANIO              NUMBER(4, 0)     NOT NULL,
    NUM_SERIE         VARCHAR2(20)     NOT NULL,
    TIPO              CHAR(1)          NOT NULL,
    PRECIO            NUMBER(9, 2)     NOT NULL,
    FECHA_STATUS      DATE             NOT NULL,
    SUCURSAL_ID       NUMBER(10, 0)    NOT NULL,    
    STATUS_AUTO_ID    NUMBER(10, 0)    NOT NULL,
    MODELO_ID         NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PK5_2 PRIMARY KEY (AUTO_ID), 
    CONSTRAINT RefMODELO_R_RDVG_S116 FOREIGN KEY (MODELO_ID)
    REFERENCES MODELO_R_RDVG_S1(MODELO_ID),
    CONSTRAINT RefSUCURSAL_F2_RDVG_S119 FOREIGN KEY (SUCURSAL_ID)
    REFERENCES SUCURSAL_F2_RDVG_S1(SUCURSAL_ID),
    CONSTRAINT RefSTATUS_AUTO20 FOREIGN KEY (STATUS_AUTO_ID)
    REFERENCES STATUS_AUTO(STATUS_AUTO_ID)
);



-- 
-- TABLE: AUTO_CARGA_F1_RDVG_S1 
--

CREATE TABLE AUTO_CARGA_F1_RDVG_S1(
    AUTO_ID             NUMBER(10, 0)    NOT NULL,
    PESO_MAXIMO         NUMBER(10, 2)    NOT NULL,
    VOLUMEN             NUMBER(10, 2)    NOT NULL,
    TIPO_COMBUSTIBLE    CHAR(1)          NOT NULL,
    CONSTRAINT PK8 PRIMARY KEY (AUTO_ID), 
    CONSTRAINT RefAUTO_F2_RDVG_S115 FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F2_RDVG_S1(AUTO_ID)
);



-- 
-- TABLE: AUTO_PARTICULAR_F1_RDVG_S1 
--

CREATE TABLE AUTO_PARTICULAR_F1_RDVG_S1(
    AUTO_ID          NUMBER(10, 0)    NOT NULL,
    NUM_CILINDROS    NUMBER(1, 0)     NOT NULL,
    NUM_PASAJEROS    NUMBER(1, 0)     NOT NULL,
    CLASE            CHAR(1)          NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (AUTO_ID), 
    CONSTRAINT RefAUTO_F2_RDVG_S114 FOREIGN KEY (AUTO_ID)
    REFERENCES AUTO_F2_RDVG_S1(AUTO_ID)
);



